print("                x                   ")
print("               xxx                  ")
print("              xxxxxx                ")
print("             xxxxxxxx               ")
print("            xxxxxxxxxxx             ")
print("           xxxxxxxxxxxxxx           ")


print("                     *                 ")
print("                   *****               ")
print("                  ********             ")
print("                 **********            ")
print("               ***************         ")
print("                 ***********           ")
print("                    *****              ")
print("                      *                ")